const projectList = {
  featuredProject: {
    id: 10,
    title: 'Rasbian Community Conference',
    short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
    full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
    live_url: 'https://skyv26.github.io/raspbian-community-conference/',
    source_url: 'https://github.com/skyv26/raspbian-community-conference',
    image: './assets/raspbian-community-conference-d.svg',
    model_image: './assets/raspbian-community-conference-d.svg',
    tags: ['html', 'scss', 'javascript'],
  },
  projectGrid: [
    {
      id: 1,
      title: 'Huddle Landing Page Single Section',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://faq-lac.vercel.app/',
      source_url: 'https://github.com/skyv26/faq-accordian-card',
      image: './assets/accordian.svg',
      model_image: './assets/accordian-d.svg',
      tags: ['react.js', 'css'],
    },
    {
      id: 2,
      title: 'Random Advice Generator App',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://skyadvice.netlify.app/',
      source_url: 'https://github.com/skyv26/advice-generator-app',
      image: './assets/random-quote.svg',
      model_image: './assets/random-advice-d.svg',
      tags: ['react.js', 'css', 'jsx'],
    },
    {
      id: 3,
      title: 'E-commerce Product Page',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://sneekers.netlify.app/',
      source_url: 'https://github.com/skyv26/sneakers',
      image: './assets/sneekers.svg',
      model_image: './assets/sneekr-d.svg',
      tags: ['react.js', 'hooks', 'styled'],
    },
    {
      id: 4,
      title: 'Interactive Pricing Component',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://skyv26.github.io/interactive-price-component/',
      source_url: 'https://github.com/skyv26/interactive-price-component',
      image: './assets/traffic-based-pricing.svg',
      model_image: './assets/Interactive-pricing-component-d.svg',
      tags: ['html', 'sass/scss', 'javascript'],
    },
    {
      id: 5,
      title: 'Intro Component With Sign-up Form',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://mysignup.netlify.app/',
      source_url: 'https://github.com/skyv26/intro-component-signup',
      image: './assets/learn-to-code-form.svg',
      model_image: './assets/intr-signup-form-d.svg',
      tags: ['react.js', 'css'],
    },
    {
      id: 6,
      title: 'Pricing Component With Toggle',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: 'https://skyv26.github.io/pricing-component-with-toggle/',
      source_url: 'https://github.com/skyv26/pricing-component-with-toggle',
      image: './assets/pricing-component.svg',
      model_image: './assets/price-component-d.svg',
      tags: ['html', 'sass/scss', 'javascript'],
    },
  ],
};

export default projectList;
