const projectList = {
  featuredProject: {
    id: 10,
    title: 'Multi-Post Stories',
    short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
    full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
    live_url: '#',
    source_url: '#',
    image: '../../assets/highlighted-project-image.svg',
    tags: ['css', 'html', 'bootstrap', 'ruby'],
  },
  projectGrid: [
    {
      id: 1,
      title: 'Profesional Art Printing Data-1',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
    {
      id: 2,
      title: 'Profesional Art Printing Data-2',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
    {
      id: 3,
      title: 'Profesional Art Printing Data-3',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
    {
      id: 4,
      title: 'Profesional Art Printing Data-4',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
    {
      id: 5,
      title: 'Profesional Art Printing Data-5',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
    {
      id: 6,
      title: 'Profesional Art Printing Data-6',
      short_desc: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
      full_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.",
      live_url: '#',
      source_url: '#',
      image: '../../assets/highlighted-project-image.svg',
      tags: ['html', 'bootstrap', 'ruby'],
    },
  ],
};

export default projectList;